var dir_480801a70b9435ca09dddac389e12203 =
[
    [ "sqlite3", "dir_94309188edad3fda0a2585483c6de0da.html", "dir_94309188edad3fda0a2585483c6de0da" ],
    [ "column.cc", "column_8cc.html", null ],
    [ "column.h", "column_8h.html", "column_8h" ],
    [ "command.cc", "command_8cc.html", null ],
    [ "command.h", "command_8h.html", "command_8h" ],
    [ "database.cc", "db_2database_8cc.html", "db_2database_8cc" ],
    [ "database.h", "db_2database_8h.html", "db_2database_8h" ],
    [ "dataset.cc", "addons_2db_2dataset_8cc.html", "addons_2db_2dataset_8cc" ],
    [ "dataset.h", "addons_2db_2dataset_8h.html", "addons_2db_2dataset_8h" ],
    [ "dbfactory.cc", "dbfactory_8cc.html", "dbfactory_8cc" ],
    [ "dbfactory.h", "dbfactory_8h.html", "dbfactory_8h" ],
    [ "dbserver.cc", "dbserver_8cc.html", "dbserver_8cc" ],
    [ "dbserver.h", "dbserver_8h.html", "dbserver_8h" ],
    [ "filterset.cc", "filterset_8cc.html", "filterset_8cc" ],
    [ "filterset.h", "db_2filterset_8h.html", "db_2filterset_8h" ],
    [ "reader.cc", "reader_8cc.html", "reader_8cc" ],
    [ "reader.h", "reader_8h.html", "reader_8h" ],
    [ "relation.cc", "relation_8cc.html", "relation_8cc" ],
    [ "relation.h", "relation_8h.html", "relation_8h" ],
    [ "table.cc", "db_2table_8cc.html", "db_2table_8cc" ],
    [ "table.h", "db_2table_8h.html", "db_2table_8h" ],
    [ "valuetable.cc", "valuetable_8cc.html", "valuetable_8cc" ],
    [ "valuetable.h", "valuetable_8h.html", "valuetable_8h" ],
    [ "writer.cc", "writer_8cc.html", "writer_8cc" ],
    [ "writer.h", "writer_8h.html", "writer_8h" ]
];